name: Setup
description: Setup ned building

runs:
  using: "composite"
  steps:
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: bky-iac
          use-mamba: true

    - name: Get date
      id: get-date
      run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash -l {0}

    - name: Setup env caching
      id: cache
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0  # increase to reset cache manually
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ hashFiles('environment.yaml', 'poetry.lock') }}-${{ steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER }}

    - name: Update environment
      run: |
        mamba env update -n bky-iac -f environment.yaml
        poetry install
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash -l {0}

    - name: Build and install
      run: |
        poetry build
        pip install .
      shell: bash -l {0}
