image: continuumio/miniconda3:latest

definitions:
  caches:
    conda: /opt/conda/envs
  steps:

    - step: &clear-cache
        name: Clear cache
        script:
          - pipe: atlassian/bitbucket-clear-cache:3.1.1
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USER_NAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              CACHES: [ "conda" ]
        condition:
          changesets:
            includePaths:
              - environment.yaml
              - poetry.lock
              - bitbucket-pipelines.yml

    - step: &setup-env
        name: Setup Environment
        caches:
          - conda
        script:
          - conda install -c conda-forge mamba
          - mamba env update -n bky-iac -f environment.yaml
          - conda activate bky-iac
          - poetry install

    - step: &test-unit
        name: Unit test
        caches:
          - conda
        script:
          - conda activate bky-iac
          - make test-unit

    - step: &test-live
        name: Live test
        caches:
          - conda
        script:
          - conda activate bky-iac
          - poetry build
          - pip install .
          - mkdir $HOME/$LIVE_DATA_DIR
          - >-
            BKY_IAC_ACCESS_KEY=$LIVE_ACCESS_KEY
            BKY_IAC_SECRET_KEY=$LIVE_SECRET_KEY
            BKY_IAC_REGION=$LIVE_REGION
            BKY_IAC_KEY_SECRETS_FOLDER=$HOME/$LIVE_DATA_DIR
            BKY_IAC_INSTANCE_SECURITY_GROUP=$LIVE_SECURITY_GROUP
            make pyiac=iac test-live
          - rm -r $HOME/$LIVE_DATA_DIR

    - step: &lint
        name: Lint
        caches:
          - conda
        script:
          - conda activate bky-iac
          - make lint

pipelines:
  default:
    - step: *clear-cache
    - step: *setup-env
    - parallel:
      - step: *test-unit
      - step: *lint
  branches:
    main:
      - step: *clear-cache
      - step: *setup-env
      - parallel:
        - step: *test-unit
        - step: *test-live
        - step: *lint

