image: continuumio/miniconda3:latest

definitions:
  caches:
    conda: /opt/conda/envs
  steps:
    - step: &clear-cache
        name: Clear cache
        script:
          - pipe: atlassian/bitbucket-clear-cache:3.1.1
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USER_NAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              CACHES: [ "conda" ]
        condition:
          changesets:
            includePaths:
              - environment.yaml
              - poetry.lock
              - bitbucket-pipelines.yml
    - step: &install
        name: Install
        caches:
          - conda
        script:
          - conda install -c conda-forge mamba
          - mamba env update -n bky-iac -f environment.yaml
          - conda activate bky-iac
          - poetry install
        condition:
          changesets:
            includePaths:
              - environment.yaml
              - poetry.lock
              - bitbucket-pipelines.yml
    - step: &test
        name: Test
        caches:
          - conda
        script:
          - conda activate bky-iac
          - make test
    - step: &lint
        name: Lint
        caches:
          - conda
        script:
          - conda activate bky-iac
          - make lint

pipelines:
  default:
    - step: *clear-cache
    - step: *install
    - parallel:
      - step: *test
      - step: *lint

