- name: Setup Nix
  hosts: all
  tasks:

    - name: Download Nix installer
      get_url:
        url: https://nixos.org/nix/install
        dest: /tmp/install-nix.sh

    - name: Run Nix installer
      command: /bin/bash /tmp/install-nix.sh --no-daemon
      args:
        creates: /nix

    - name: Create a simple shell configuration
      copy:
        dest: /home/ec2-user/shell.nix
        content: |
          let
            nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.11";
            pkgs = import nixpkgs { config = {}; overlays = []; };
          in

          pkgs.mkShellNoCC {
            packages = with pkgs; [
              git
              gh
              go

              # add more packages or remove the ones that you don't think are useful
            ];
          }
