[iac.aws]
# Name of the credentials file in the "setup" folder
cred_file = "string.csv"
# Name of the EC2 instance to be managed by IAC - globally unique
instance_name = "string"
# Name of the EC2 key to use for connections to EC2 instances
key_name = "string"
# Name of the AWS region for new EC2 instances
region = "string"
# Name of the AWS security group for new EC2 instances
security_group = "string"



